name: "publish"

on: 
    puch: 
        branch:
        master

        jobs:
          release:
               name: publish
                 runs-on: ubuntu-latest
                 steps:
                    name: checkout 
                    uses: actions/checkout@v2.1.1
                    name: actions/setup-node@v1.4.2
                    with: 
                      node-version: 12
                      registry-url: https://registry.npmjs.org
                      name: publish
                      run: npm publish --access public
                      env: 
                      VSCE_PAT: ${{secrrets.VSCE_PAT}}
