name: publish
on:
  push:
    types:
      - 'master'
jobs:
  release:
    name: publish
    if: ${{ github.repository == 'primer/github-vscode-theme' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
      

      
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

        id: changesets
        uses: changesets/action@master
        with:
          title: Release Tracking
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        