name: "publish"

on: 
    release: 
        types: [published]

        jobs:
          release:
               name: publish
                 runs-on: ubuntu-latest
                 steps:
                    name: checkout 
                    uses: actions/checkout@v2.1.1
                    name: actions/setup-node@v1.4.2
                    with: 
                      node-version: 12
                      registry-url: 
                      name: publish
                      run: npm publish --access public
                      working-directory: my-package
                      env: 
                      NODE_AUTH_TOKEN: ${{secrrets.NPM_AUTH_TOKEN}}
