name: publish

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      name: Install Node.js
      - uses: actions/setup-node@v1
      - run: npm install
      name: Publish
      run: npm run deploy
      - env:
          VSCE_PUBLISHER_TOKEN: ${{ secrets.VSCE_PAT }}
        